# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26613f486156d860272b319a3a6bf8d8a9a42504a762d75f7bce6f92483f8670f12f4416f302af9bf6ebdf00b82e964b96ed040239897a053e22f00d28273f3d

test:
  secret_key_base: b39e5916cf53fc4ba3683f6bbcda763c2344d26aac046fd4b43603cd51174024b25859cf9c6542492c97720aa56f0a9f7989ecd79f549480d9a3c05ff1453f74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
